import SingleUser from "@/components/Feed/SingleUser";
import React from "react";
export const metadata = {
  title: "Single user",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <SingleUser />
    </div>
  );
};

export default page;
