import CreateData from "@/components/Feed/CreateData";
import React from "react";
export const metadata = {
  title: "Create Account",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <CreateData />
    </div>
  );
};

export default page;
