import FormData from "@/components/Feed/FormData";
import React from "react";
export const metadata = {
  title: "Log in a user.",
  description: "Generated by create next app",
};
const login = () => {
  return (
    <div>
      <FormData />
    </div>
  );
};

export default login;
