import UploadPage from "@/components/Feed/Upload-page";
import React from "react";
export const metadata = {
  title: "Update a user post.",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div className="grid h-screen place-items-center">
      <UploadPage />
    </div>
  );
};

export default page;
