import UpdateForm from "@/components/Feed/UpdateForm";
import React from "react";
export const metadata = {
  title: "Edit Post",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div className="grid h-screen place-items-center">
      <UpdateForm />
    </div>
  );
};

export default page;
