import EditProfile from "@/components/Feed/EditProfile";
export const metadata = {
  title: "Update Your Post.",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <EditProfile />
    </div>
  );
};

export default page;
