import Profile from "@/components/Feed/Profile";
import React from "react";
export const metadata = {
  title: "User Profile.",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <Profile />
    </div>
  );
};

export default page;
